const products = [
    // =========================================================================
    // 1. STAINLESS STEEL - 300 SERIES (AUSTENITIC)
    // =========================================================================
    {
        id: "ss-202-j4",
        department: "Stainless Steel 200",
        grade: "SS 202 (Jindal J4)",
        image: "https://placehold.co/600x400/cbd5e1/000000?text=Jindal+J4",
        category: "Flat Products",
        forms: ["Sheets", "Coils", "Patta", "Circles"],
        description: "The gold standard for 200 series. High Copper content for deep drawing. Non-magnetic.",
        chem: { "Cr": "15-17%", "Ni": "1.0-1.5%", "Cu": "1.5-2.0%", "Mn": "8-10%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["Jindal J4", "IS 6911"], range: "0.1mm to 4.0mm" },
        pros: "Closest alternative to 304 at lower cost.",
        cons: "Not for coastal use."
    },
    {
        id: "ss-202-j1",
        department: "Stainless Steel 200",
        grade: "SS 202 (Jindal J1)",
        image: "https://placehold.co/600x400/cbd5e1/000000?text=Jindal+J1",
        category: "Flat Products",
        forms: ["Sheets", "Coils"],
        description: "Cost-effective grade for shallow drawing. Used in utensils and kitchenware.",
        chem: { "Cr": "13-15%", "Ni": "0.2-0.6%", "Cu": "0.5-1.0%", "Mn": "8-10%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["Jindal J1"], range: "Stock" },
        pros: "Very economical.",
        cons: "Lower corrosion resistance than J4."
    },
    {
        id: "ss-202-j2",
        department: "Stainless Steel 200",
        grade: "SS 202 (Jindal J2)",
        image: "https://placehold.co/600x400/cbd5e1/000000?text=Jindal+J2",
        category: "Flat Products",
        forms: ["Sheets", "Coils"],
        description: "Standard grade for general fabrication and cookware.",
        chem: { "Cr": "14-16%", "Ni": "0.3-0.7%", "Cu": "0.5-1.0%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["Jindal J2"], range: "Stock" },
        pros: "Balanced price/performance.",
        cons: "Work hardens quickly."
    },
    {
        id: "ss-202-j3",
        department: "Stainless Steel 200",
        grade: "SS 202 (Jindal J3)",
        image: "https://placehold.co/600x400/cbd5e1/000000?text=Jindal+J3",
        category: "Flat Products",
        forms: ["Sheets", "Strips"],
        description: "Hard grade for structural applications like furniture frames.",
        chem: { "Cr": "13-15%", "Ni": "0.1-0.4%", "Mn": "9-11%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["Jindal J3"], range: "Stock" },
        pros: "High strength.",
        cons: "Poor drawing capability."
    },
    {
        id: "ss-201",
        department: "Stainless Steel 200",
        grade: "SS 201 (JT)",
        image: "https://placehold.co/600x400/cbd5e1/000000?text=SS+201",
        category: "Pipes & Tubes",
        forms: ["Decorative Pipes", "Rods"],
        description: "High Manganese, Nitrogen strengthened. Used for decorative tubes and railings.",
        chem: { "Cr": "16-18%", "Ni": "0.5-1.0%", "Mn": "5.5-7.5%" },
        phys: { "Density": "7.86 g/cm³" },
        specs: { standards: ["ASTM A240"], range: "Round/Square Pipes" },
        pros: "Excellent yield strength.",
        cons: "Susceptible to rust spots outdoors."
    },
    {
        id: "ss-204-cu",
        department: "Stainless Steel 200",
        grade: "SS 204Cu",
        image: "https://placehold.co/600x400/cbd5e1/000000?text=SS+204Cu",
        category: "Bars & Rods",
        forms: ["Rods", "Wire", "Fasteners"],
        description: "Premium 200 series with 2-3% Copper. Ideal for making screws and fasteners.",
        chem: { "Cr": "16-17%", "Ni": "1.5-3.0%", "Cu": "2.0-3.5%" },
        phys: { "Density": "7.84 g/cm³" },
        specs: { standards: ["ASTM A276"], range: "Cold Heading Quality" },
        pros: "Superior cold heading properties.",
        cons: "Higher cost than 202."
    },
    {
        id: "ss-202-flat",
        department: "Stainless Steel 200",
        grade: "SS 202 Flat Bar (Patti)",
        image: "https://placehold.co/600x400/cbd5e1/000000?text=202+Patti",
        category: "Bars & Rods",
        forms: ["Flat Bars", "Angles"],
        description: "Slit edge or mill edge flats for gates, grills, and structural fabrication.",
        chem: { "Ni": "0.5-1.5%", "Cr": "14-16%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["Commercial"], range: "12mm to 100mm Width" },
        pros: "Cheap structural material.",
        cons: "Requires polish to maintain shine."
    },
    {
        
        id: "ss-304-series",
        department: "Stainless Steel",
        grade: "SS 304 / 304L",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SS+304+Pipes",
        category: "Pipes & Tubes",
        forms: ["Seamless Pipes", "ERW Pipes", "Sheets", "Plates", "Coils", "Hex Bar"],
        description: "The most versatile stainless steel. Dual Certified (304/304L) for general corrosion resistance.",
        chem: { "Cr": "18-20%", "Ni": "8-10.5%", "C": "0.08%" },
        phys: { "Density": "7.93 g/cm³" },
        specs: { standards: ["ASTM A312", "ASTM A240", "ASTM A276"], range: "Full Range" },
        pros: "Excellent formability, food-safe.",
        cons: "Pits in salt environments."
    },
    {
        id: "ss-304h",
        department: "Stainless Steel",
        grade: "SS 304H",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SS+304H",
        category: "Pipes & Tubes",
        forms: ["Seamless Pipes", "Plates", "Round Bars"],
        description: "High carbon version of 304 for high-temperature service (above 800°F).",
        chem: { "Cr": "18-20%", "Ni": "8-10.5%", "C": "0.04-0.10%" },
        phys: { "Density": "7.93 g/cm³" },
        specs: { standards: ["ASTM A312"], range: "Custom" },
        pros: "Higher creep strength than 304L.",
        cons: "Lower corrosion resistance."
    },
    {
        id: "ss-316-series",
        department: "Stainless Steel",
        grade: "SS 316 / 316L",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SS+316+Marine",
        category: "Pipes & Tubes",
        forms: ["Seamless Pipes", "Plates", "Rods", "Fittings", "Hex Bar"],
        description: "Molybdenum-bearing marine grade. Excellent resistance to chlorides and acids.",
        chem: { "Cr": "16-18%", "Ni": "10-14%", "Mo": "2-3%" },
        phys: { "Density": "7.98 g/cm³" },
        specs: { standards: ["ASTM A312", "ASTM A240"], range: "Full Range" },
        pros: "Superior corrosion resistance.",
        cons: "Higher cost."
    },
    {
        id: "ss-316ti",
        department: "Stainless Steel",
        grade: "SS 316Ti",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SS+316Ti",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Rods"],
        description: "Titanium stabilized version of 316. Prevents sensitization during welding.",
        chem: { "Mo": "2-3%", "Ti": "5x(C+N)" },
        phys: { "Density": "7.98 g/cm³" },
        specs: { standards: ["ASTM A312"], range: "Custom" },
        pros: "Good for long term heat exposure.",
        cons: "Harder to machine."
    },
    {
        id: "ss-317l",
        department: "Stainless Steel",
        grade: "SS 317L",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SS+317L",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Plates"],
        description: "High Molybdenum (3-4%) content. Essential for chemical scrubbers.",
        chem: { "Mo": "3-4%", "Ni": "11-15%" },
        phys: { "Density": "8.00 g/cm³" },
        specs: { standards: ["ASTM A312"], range: "Stock" },
        pros: "Better pitting resistance.",
        cons: "Specialized inventory."
    },
    {
        id: "ss-321",
        department: "Stainless Steel",
        grade: "SS 321",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SS+321",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Sheets", "Flanges"],
        description: "Titanium stabilized. Used in aircraft exhaust and heat exchangers.",
        chem: { "Ti": "5xC", "Cr": "17-19%" },
        phys: { "Density": "7.92 g/cm³" },
        specs: { standards: ["ASTM A312", "ASTM A240"], range: "Stock" },
        pros: "Resists intergranular corrosion.",
        cons: "Cannot be mirror polished."
    },
    {
        id: "ss-347",
        department: "Stainless Steel",
        grade: "SS 347",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SS+347",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Rods"],
        description: "Niobium stabilized. Used in refineries and high temp chemical processing.",
        chem: { "Nb": "10xC", "Cr": "17-19%" },
        phys: { "Density": "7.96 g/cm³" },
        specs: { standards: ["ASTM A312"], range: "Custom" },
        pros: "Superior to 321 in oxidation resistance.",
        cons: "Higher cost due to Niobium."
    },
    {
        id: "ss-310s",
        department: "Stainless Steel",
        grade: "SS 310S High Temp",
        image: "https://placehold.co/600x400/b91c1c/ffffff?text=SS+310S",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Plates", "Rods"],
        description: "The standard for high temperature service up to 1150°C. Furnace parts.",
        chem: { "Cr": "24-26%", "Ni": "19-22%" },
        phys: { "Density": "7.98 g/cm³" },
        specs: { standards: ["ASTM A312", "ASTM A240"], range: "Stock" },
        pros: "Best oxidation resistance.",
        cons: "Prone to embrittlement."
    },
    {
        id: "ss-904l",
        department: "Stainless Steel",
        grade: "SS 904L",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SS+904L",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Fittings"],
        description: "Super austenitic stainless steel for sulfuric acid service. Rolex steel.",
        chem: { "Ni": "23-28%", "Mo": "4-5%", "Cu": "1-2%" },
        phys: { "Density": "8.00 g/cm³" },
        specs: { standards: ["ASTM A312"], range: "Imported" },
        pros: "Excellent acid resistance.",
        cons: "Very expensive."
    },
    {
        id: "ss-254smo",
        department: "Stainless Steel",
        grade: "SMO 254 (6% Moly)",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=SMO+254",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Plates"],
        description: "High alloy austenitic steel for seawater handling.",
        chem: { "Mo": "6-6.5%", "N": "0.18-0.22%" },
        phys: { "Density": "8.00 g/cm³" },
        specs: { standards: ["ASTM A312"], range: "Imported" },
        pros: "Replaces Titanium in some uses.",
        cons: "High cost."
    },

    // =========================================================================
    // 2. STAINLESS STEEL - 400 SERIES (FERRITIC/MARTENSITIC)
    // =========================================================================
    {
        id: "ss-409",
        department: "Stainless Steel",
        grade: "SS 409 / 409M",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=SS+409",
        category: "Flat Products",
        forms: ["Sheets", "Coils"],
        description: "Automotive exhaust grade. Low cost ferritic steel.",
        chem: { "Cr": "10.5-11.7%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A240"], range: "Sheets" },
        pros: "Cheapest stainless steel.",
        cons: "Surface rusts easily."
    },
    {
        id: "ss-410",
        department: "Stainless Steel",
        grade: "SS 410",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=SS+410",
        category: "Bars & Rods",
        forms: ["Rods", "Plates", "Hex Bar"],
        description: "Martensitic grade. Can be heat treated for high hardness.",
        chem: { "Cr": "11.5-13.5%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A276"], range: "Rods" },
        pros: "High strength and hardness.",
        cons: "Low corrosion resistance."
    },
    {
        id: "ss-420",
        department: "Stainless Steel",
        grade: "SS 420",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=SS+420",
        category: "Bars & Rods",
        forms: ["Rods", "Strips"],
        description: "Cutlery grade stainless steel. Higher carbon than 410.",
        chem: { "Cr": "12-14%", "C": "0.15% Min" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A276"], range: "Stock" },
        pros: "Excellent wear resistance.",
        cons: "Lower corrosion resistance than 304; brittle if not tempered properly."
    },
    {
        id: "ss-430",
        department: "Stainless Steel",
        grade: "SS 430",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=SS+430",
        category: "Flat Products",
        forms: ["Sheets", "Coils"],
        description: "Ferritic grade. Standard for indoor trim and appliances.",
        chem: { "Cr": "16-18%", "Ni": "0%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A240"], range: "Sheets" },
        pros: "Magnetic, good formability.",
        cons: "Not for welding."
    },
    {
        id: "ss-431",
        department: "Stainless Steel",
        grade: "SS 431",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=SS+431",
        category: "Bars & Rods",
        forms: ["Rods", "Hex Bar"],
        description: "Best corrosion resistance of all martensitic grades.",
        chem: { "Cr": "15-17%", "Ni": "1.25-2.5%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A276"], range: "Stock" },
        pros: "High toughness.",
        cons: "Difficult to weld; prone to temper embrittlement."
    },
    {
        id: "ss-446",
        department: "Stainless Steel",
        grade: "SS 446",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=SS+446",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Rods"],
        description: "High chromium ferritic heat resistant alloy.",
        chem: { "Cr": "23-27%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A268"], range: "Custom" },
        pros: "Resists sulfur gas at high temp.",
        cons: "Difficult to fabricate."
    },
    {
        id: "ss-17-4ph",
        department: "Stainless Steel",
        grade: "17-4 PH",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=17-4+PH",
        category: "Bars & Rods",
        forms: ["Round Bars", "Hex Bar", "Square Bar"],
        description: "Precipitation Hardening grade. High strength and corrosion resistance.",
        chem: { "Cr": "15-17.5%", "Ni": "3-5%", "Cu": "3-5%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A564"], range: "Stock" },
        pros: "Aerospace standard.",
        cons: "High pricing; susceptible to stress corrosion cracking if under-aged."
    },
    {
        id: "ss-15-5ph",
        department: "Stainless Steel",
        grade: "15-5 PH (XM-12)",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=15-5+PH",
        category: "Bars & Rods",
        forms: ["Round Bars"],
        description: "Variant of 17-4PH with better transverse toughness.",
        chem: { "Cr": "14-15.5%", "Ni": "3.5-5.5%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A564", "AMS 5659"], range: "Custom" },
        pros: "Uniform structure.",
        cons: "Higher material cost; requires precise age-hardening heat treatments."
    },

    // =========================================================================
    // 3. DUPLEX & SUPER DUPLEX STEEL
    // =========================================================================
    {
        id: "duplex-2205",
        department: "Duplex Steel",
        grade: "Duplex 2205 (UNS S31803)",
        image: "https://placehold.co/600x400/0f172a/ffffff?text=Duplex+2205",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Plates", "Flanges", "Round Bar"],
        description: "The most widely used duplex grade. Twice the yield strength of 316.",
        chem: { "Cr": "22%", "Mo": "3%", "Ni": "5%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A790", "ASTM A182"], range: "Sch 10-160" },
        pros: "Resists stress corrosion cracking.",
        cons: "Limit use to below 300°C."
    },
    {
        id: "lean-duplex",
        department: "Duplex Steel",
        grade: "Lean Duplex (UNS S32304)",
        image: "https://placehold.co/600x400/0f172a/ffffff?text=Lean+Duplex",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Sheets"],
        description: "Cost-effective duplex. Replaces 304/316 in bridges and tanks.",
        chem: { "Cr": "23%", "Ni": "4%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A240"], range: "Stock" },
        pros: "Higher strength than 316.",
        cons: "Lower Molybdenum."
    },
    {
        id: "super-duplex-2507",
        department: "Duplex Steel",
        grade: "Super Duplex 2507",
        image: "https://placehold.co/600x400/0f172a/ffffff?text=SDSS+2507",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Plates", "Rods"],
        description: "For extremely corrosive conditions like desalination and offshore oil.",
        chem: { "Cr": "25%", "Mo": "4%", "Ni": "7%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A790"], range: "Stock" },
        pros: "Excellent in seawater.",
        cons: "Expensive."
    },
    {
        id: "super-duplex-32760",
        department: "Duplex Steel",
        grade: "Super Duplex 32760 (Zeron 100)",
        image: "https://placehold.co/600x400/0f172a/ffffff?text=Zeron+100",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Fittings"],
        description: "Super Duplex with added Tungsten for pitting resistance.",
        chem: { "Cr": "25%", "W": "0.5-1.0%" },
        phys: { "Density": "7.80 g/cm³" },
        specs: { standards: ["ASTM A790"], range: "Custom" },
        pros: "High critical pitting temp.",
        cons: "Strict temperature control needed during multi-pass welding to prevent sigma phases."
    },

    // =========================================================================
    // 4. CARBON STEEL (PIPES & PLATES)
    // =========================================================================
    {
        id: "cs-a106-b",
        department: "Carbon Steel",
        grade: "ASTM A106 Grade B",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=A106+Gr.B",
        category: "Pipes & Tubes",
        forms: ["Seamless Pipes"],
        description: "Standard seamless carbon steel pipe for high-temperature service.",
        chem: { "C": "0.30% Max", "Mn": "0.29-1.06%" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A106"], range: "1/2\" to 24\" NB" },
        pros: "Industry workhorse.",
        cons: "Requires painting."
    },
    {
        id: "cs-a53-b",
        department: "Carbon Steel",
        grade: "ASTM A53 Grade B",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=A53+Gr.B",
        category: "Pipes & Tubes",
        forms: ["ERW Pipes", "Seamless Pipes"],
        description: "Standard pipe for structural, water, and low pressure uses.",
        chem: { "C": "0.30% Max" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A53"], range: "Stock" },
        pros: "Cost effective.",
        cons: "Lower pressure rating than A106."
    },
    {
        id: "cs-api5l-x-series",
        department: "Carbon Steel",
        grade: "API 5L X42 / X52 / X60 / X65",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=API+5L+Pipes",
        category: "Pipes & Tubes",
        forms: ["Line Pipes"],
        description: "High yield line pipe for oil and gas transmission.",
        chem: { "Mn": "1.4% Max" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["API 5L PSL1/PSL2"], range: "Stock" },
        pros: "High pressure lines.",
        cons: "Prone to atmospheric corrosion; requires rust-inhibitive coatings."
    },
    {
        id: "cs-a333-6",
        department: "Carbon Steel",
        grade: "ASTM A333 Grade 6 (LTCS)",
        image: "https://placehold.co/600x400/0f172a/ffffff?text=LTCS+Gr6",
        category: "Pipes & Tubes",
        forms: ["Seamless Pipes", "Fittings"],
        description: "Low Temp Carbon Steel (LTCS). Impact tested at -45°C.",
        chem: { "C": "0.30% Max" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A333"], range: "Stock" },
        pros: "Cryogenic use.",
        cons: "Requires proper protective lagging to avoid corrosion under insulation (CUI)."
    },
    {
        id: "cs-a105",
        department: "Carbon Steel",
        grade: "ASTM A105 Forging",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=A105+Forging",
        category: "Fittings & Flanges",
        forms: ["Flanges", "Forged Fittings", "Round Bar"],
        description: "Standard carbon steel forging material.",
        chem: { "C": "0.35% Max" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A105"], range: "Full Range" },
        pros: "Universal flange material.",
        cons: "Not suitable for low-temperature service or marine atmosphere without zinc coating."
    },
    {
        id: "cs-lf2",
        department: "Carbon Steel",
        grade: "ASTM A350 LF2",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=LF2+Flange",
        category: "Fittings & Flanges",
        forms: ["Flanges", "Round Bar"],
        description: "Low temp carbon steel forging. Matches A333 pipe.",
        chem: { "C": "0.30% Max" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A350"], range: "Stock" },
        pros: "Good notch toughness.",
        cons: "Susceptible to general rust; requires surface primer/galvanizing."
    },
    {
        id: "cs-is2062",
        department: "Carbon Steel",
        grade: "IS 2062 Grade B (Mild Steel)",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=IS+2062",
        category: "Flat Products",
        forms: ["Plates", "Structurals", "Angles"],
        description: "Standard Indian structural steel.",
        chem: { "C": "0.22% Max" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["IS 2062"], range: "Full Range" },
        pros: "Available and cheap.",
        cons: "Low corrosion resistance; must be painted or hot-dip galvanized."
    },
    {
        id: "st-52-3",
        department: "Carbon Steel",
        grade: "ST 52.3",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=ST+52.3",
        category: "Bars & Rods",
        forms: ["Round Bars", "Hollow Bars"],
        description: "High tensile low carbon manganese steel.",
        chem: { "C": "0.22% Max", "Mn": "1.6% Max" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["DIN 17100"], range: "Stock" },
        pros: "Good weldability.",
        cons: "No native corrosion resistance; requires external protection."
    },

    // =========================================================================
    // 5. ALLOY STEEL & ENGINEERING STEEL (EN SERIES)
    // =========================================================================
    {
        id: "alloy-p11-p22",
        department: "Alloy Steel",
        grade: "Alloy P11 / P22 / P5 / P9",
        image: "https://placehold.co/600x400/64748b/ffffff?text=Chrome+Moly",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Fittings"],
        description: "Chrome-Moly pipes for Power Plants. P11/P22 (Boiler Steam), P5/P9 (Refinery).",
        chem: { "Cr": "1-9%", "Mo": "0.5-1.0%" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A335"], range: "Full Range" },
        pros: "Excellent creep strength.",
        cons: "Requires PWHT."
    },
    {
        id: "alloy-p91",
        department: "Alloy Steel",
        grade: "Alloy P91 (T91)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=Alloy+P91",
        category: "Pipes & Tubes",
        forms: ["Pipes"],
        description: "Modified 9Cr-1MoV. For supercritical power plants.",
        chem: { "V": "0.18-0.25%", "Nb": "0.06-0.10%" },
        phys: { "Density": "7.77 g/cm³" },
        specs: { standards: ["ASTM A335"], range: "Imported" },
        pros: "Highest creep strength.",
        cons: "Complex welding."
    },
    {
        id: "en-8",
        department: "Alloy Steel",
        grade: "EN8 (AISI 1045)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=EN8+Rod",
        category: "Bars & Rods",
        forms: ["Round Bars", "Hex Bars"],
        description: "Unalloyed medium carbon steel. Used for axles, shafts, gears.",
        chem: { "C": "0.36-0.44%" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["BS 970"], range: "Stock" },
        pros: "Good tensile strength.",
        cons: "Poor through-hardenability in heavy diameters; lacks corrosion resistance."
    },
    {
        id: "en-9",
        department: "Alloy Steel",
        grade: "EN9 (AISI 1055)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=EN9+Rod",
        category: "Bars & Rods",
        forms: ["Round Bars"],
        description: "Surface hardenable carbon steel. Used for sprockets and cams.",
        chem: { "C": "0.50-0.60%" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["BS 970"], range: "Stock" },
        pros: "Wear resistance.",
        cons: "Very low weldability; cracking likely if preheating is ignored."
    },
    {
        id: "en-19",
        department: "Alloy Steel",
        grade: "EN19 (AISI 4140)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=EN19+Rod",
        category: "Bars & Rods",
        forms: ["Round Bars", "Plates"],
        description: "High tensile alloy steel. 1% Chromium Molybdenum.",
        chem: { "Cr": "0.9-1.2%", "Mo": "0.15-0.30%" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["BS 970"], range: "Stock" },
        pros: "Good shock resistance.",
        cons: "Temper embrittlement risk if slow-cooled between 500-600°C."
    },
    {
        id: "en-24",
        department: "Alloy Steel",
        grade: "EN24 (AISI 4340)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=EN24+Rod",
        category: "Bars & Rods",
        forms: ["Round Bars"],
        description: "Nickel-Chrome-Moly steel. High strength and toughness.",
        chem: { "Ni": "1.3-1.8%", "Cr": "0.9-1.4%" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["BS 970"], range: "Stock" },
        pros: "Deep hardenability.",
        cons: "Excellent strength makes machining highly difficult and expensive post-heat treat."
    },
    {
        id: "en-31",
        department: "Alloy Steel",
        grade: "EN31 (SAE 52100)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=EN31+Rod",
        category: "Bars & Rods",
        forms: ["Round Bars"],
        description: "High carbon chrome steel. Ball bearing quality.",
        chem: { "C": "0.95-1.1%", "Cr": "1.2-1.6%" },
        phys: { "Density": "7.81 g/cm³" },
        specs: { standards: ["BS 970"], range: "Stock" },
        pros: "Extreme hardness (60-66 HRC).",
        cons: "Low impact toughness; susceptible to chipping if subjected to heavy shock."
    },
    {
        id: "aisi-4130",
        department: "Alloy Steel",
        grade: "AISI 4130",
        image: "https://placehold.co/600x400/64748b/ffffff?text=AISI+4130",
        category: "Bars & Rods",
        forms: ["Rods", "Plates"],
        description: "Chromoly steel. High strength to weight.",
        chem: { "Cr": "0.8-1.1%", "Mo": "0.15-0.25%" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["AISI 4130"], range: "Stock" },
        pros: "Motorsports standard.",
        cons: "Lower corrosion resistance than stainless grades; requires plating/coating."
    },
    {
        id: "tool-steel-d2",
        department: "Alloy Steel",
        grade: "D2 Tool Steel",
        image: "https://placehold.co/600x400/64748b/ffffff?text=D2+Steel",
        category: "Bars & Rods",
        forms: ["Flats", "Rounds"],
        description: "High carbon, high chrome tool steel. Air hardening.",
        chem: { "Cr": "12%", "C": "1.5%" },
        phys: { "Density": "7.70 g/cm³" },
        specs: { standards: ["ASTM A681"], range: "Stock" },
        pros: "Maximum wear resistance.",
        cons: "Prone to edge chipping; difficult to grind and heat treat."
    },
    {
        id: "tool-steel-d3",
        department: "Alloy Steel",
        grade: "D3 Tool Steel",
        image: "https://placehold.co/600x400/64748b/ffffff?text=D3+Steel",
        category: "Bars & Rods",
        forms: ["Rounds", "Flats"],
        description: "Oil hardening high chrome tool steel.",
        chem: { "Cr": "12%", "C": "2%" },
        phys: { "Density": "7.70 g/cm³" },
        specs: { standards: ["ASTM A681"], range: "Stock" },
        pros: "High compressive strength.",
        cons: "High risk of cracking during rapid oil quenching; very brittle."
    },

    // =========================================================================
    // 6. NICKEL ALLOYS (INCONEL, MONEL, HASTELLOY)
    // =========================================================================
    {
        id: "inconel-600",
        department: "Nickel Alloys",
        grade: "Inconel 600",
        image: "https://placehold.co/600x400/4c1d95/ffffff?text=Inconel+600",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Rods", "Plates"],
        description: "Nickel-Chromium alloy. Resists oxidation up to 2000°F.",
        chem: { "Ni": "72% Min", "Cr": "14-17%" },
        phys: { "Density": "8.47 g/cm³" },
        specs: { standards: ["ASTM B167"], range: "Custom" },
        pros: "Immune to chloride stress corrosion.",
        cons: "Extremely high cost; difficult to machine, causing rapid tool wear."
    },
    {
        id: "inconel-601",
        department: "Nickel Alloys",
        grade: "Inconel 601",
        image: "https://placehold.co/600x400/4c1d95/ffffff?text=Inconel+601",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Plates"],
        description: "Added Aluminum for outstanding oxidation resistance.",
        chem: { "Al": "1-1.7%", "Ni": "58-63%" },
        phys: { "Density": "8.11 g/cm³" },
        specs: { standards: ["ASTM B167"], range: "Imported" },
        pros: "Best for furnaces.",
        cons: "Prone to rapid sulfur embrittlement in reducing sulfurous atmospheres."
    },
    {
        id: "inconel-625",
        department: "Nickel Alloys",
        grade: "Inconel 625",
        image: "https://placehold.co/600x400/4c1d95/ffffff?text=Inconel+625",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Sheets", "Rods", "Bolts"],
        description: "Ni-Cr-Mo-Nb alloy. High strength without heat treatment.",
        chem: { "Mo": "8-10%", "Nb": "3.15-4.15%" },
        phys: { "Density": "8.44 g/cm³" },
        specs: { standards: ["ASTM B444"], range: "Stock" },
        pros: "Excellent fatigue strength.",
        cons: "Expensive."
    },
    {
        id: "inconel-718",
        department: "Nickel Alloys",
        grade: "Inconel 718",
        image: "https://placehold.co/600x400/4c1d95/ffffff?text=Inconel+718",
        category: "Bars & Rods",
        forms: ["Rods", "Fasteners"],
        description: "Precipitation hardenable. Jet engine standard.",
        chem: { "Nb": "4.75-5.5%", "Mo": "2.8-3.3%" },
        phys: { "Density": "8.19 g/cm³" },
        specs: { standards: ["AMS 5662"], range: "Rods" },
        pros: "High strength up to 1300°F.",
        cons: "Hard to machine."
    },
    {
        id: "incoloy-800",
        department: "Nickel Alloys",
        grade: "Incoloy 800 / 800H",
        image: "https://placehold.co/600x400/7c3aed/ffffff?text=Incoloy+800",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Plates"],
        description: "Ni-Fe-Cr alloy. Resist carburization.",
        chem: { "Ni": "30-35%", "Cr": "19-23%" },
        phys: { "Density": "7.94 g/cm³" },
        specs: { standards: ["ASTM B407"], range: "Stock" },
        pros: "Stable structure at high temp.",
        cons: "Prone to sigma phase precipitation under long heat exposure below 700°C."
    },
    {
        id: "incoloy-825",
        department: "Nickel Alloys",
        grade: "Incoloy 825",
        image: "https://placehold.co/600x400/7c3aed/ffffff?text=Incoloy+825",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Round Bar"],
        description: "Added Moly and Copper. Resists sulfuric and phosphoric acid.",
        chem: { "Mo": "2.5-3.5%", "Cu": "1.5-3%" },
        phys: { "Density": "8.14 g/cm³" },
        specs: { standards: ["ASTM B423"], range: "Custom" },
        pros: "Acid resistance.",
        cons: "High price; inferior pitting resistance to super duplex steels."
    },
    {
        id: "monel-400",
        department: "Nickel Alloys",
        grade: "Monel 400",
        image: "https://placehold.co/600x400/5b21b6/ffffff?text=Monel+400",
        category: "Bars & Rods",
        forms: ["Rods", "Sheets", "U-Bolts"],
        description: "Ni-Cu alloy. Seawater and steam resistant.",
        chem: { "Ni": "63% Min", "Cu": "28-34%" },
        phys: { "Density": "8.80 g/cm³" },
        specs: { standards: ["ASTM B164"], range: "Stock" },
        pros: "Excellent in flowing seawater.",
        cons: "Magnetic."
    },
    {
        id: "monel-k500",
        department: "Nickel Alloys",
        grade: "Monel K-500",
        image: "https://placehold.co/600x400/5b21b6/ffffff?text=Monel+K500",
        category: "Bars & Rods",
        forms: ["Rods"],
        description: "Age hardened Monel 400. 3x Yield strength.",
        chem: { "Al": "2.3-3.15%", "Ti": "0.35-0.85%" },
        phys: { "Density": "8.44 g/cm³" },
        specs: { standards: ["QQ-N-286"], range: "Rods" },
        pros: "High strength marine shafts.",
        cons: "Crack prone during heat treat."
    },
    {
        id: "hastelloy-c276",
        department: "Nickel Alloys",
        grade: "Hastelloy C-276",
        image: "https://placehold.co/600x400/6d28d9/ffffff?text=Hastelloy+C276",
        category: "Flat Products",
        forms: ["Plates", "Pipes", "Fittings"],
        description: "The most versatile corrosion resistant alloy available.",
        chem: { "Mo": "15-17%", "W": "3-4.5%" },
        phys: { "Density": "8.89 g/cm³" },
        specs: { standards: ["ASTM B575"], range: "Stock" },
        pros: "Resists wet chlorine gas.",
        cons: "Expensive."
    },
    {
        id: "hastelloy-b2",
        department: "Nickel Alloys",
        grade: "Hastelloy B-2",
        image: "https://placehold.co/600x400/6d28d9/ffffff?text=Hastelloy+B2",
        category: "Bars & Rods",
        forms: ["Rods"],
        description: "High Moly alloy for hydrochloric acid.",
        chem: { "Mo": "26-30%", "Ni": "Balance" },
        phys: { "Density": "9.22 g/cm³" },
        specs: { standards: ["ASTM B335"], range: "Imported" },
        pros: "Best for HCl acid.",
        cons: "Poor in oxidizing acids."
    },
    {
        id: "nickel-200",
        department: "Nickel Alloys",
        grade: "Nickel 200 / 201",
        image: "https://placehold.co/600x400/4c1d95/ffffff?text=Nickel+200",
        category: "Flat Products",
        forms: ["Sheets", "Wires", "Rods"],
        description: "Commercially pure Nickel (99.6%).",
        chem: { "Ni": "99.6% Min" },
        phys: { "Density": "8.89 g/cm³" },
        specs: { standards: ["ASTM B160"], range: "Stock" },
        pros: "Caustic soda handling.",
        cons: "Soft."
    },
    {
        id: "alloy-20",
        department: "Nickel Alloys",
        grade: "Alloy 20 (Carpenter 20)",
        image: "https://placehold.co/600x400/4c1d95/ffffff?text=Alloy+20",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Fasteners"],
        description: "Developed specifically for sulfuric acid.",
        chem: { "Ni": "32-38%", "Cr": "19-21%" },
        phys: { "Density": "8.08 g/cm³" },
        specs: { standards: ["ASTM B729"], range: "Stock" },
        pros: "Resists acid attack.",
        cons: "Prone to intergranular corrosion in the heat-affected zone of heavy weldments unless stabilized."
    },
    {
        id: "alloy-a286",
        department: "Nickel Alloys",
        grade: "Alloy A-286 (Inconel 660)",
        image: "https://placehold.co/600x400/4c1d95/ffffff?text=Alloy+A286",
        category: "Bars & Rods",
        forms: ["Rods", "Fasteners"],
        description: "Iron-based superalloy. High strength and corrosion resistance.",
        chem: { "Ni": "24-27%", "Cr": "13.5-16%" },
        phys: { "Density": "7.92 g/cm³" },
        specs: { standards: ["AMS 5737"], range: "Rods" },
        pros: "Jet engine fasteners.",
        cons: "Requires precise solution treatment and precipitation hardening to achieve full mechanical properties."
    },

    // =========================================================================
    // 7. NON-FERROUS METALS (TITANIUM, COPPER, ALUMINUM)
    // =========================================================================
    {
        id: "ti-gr2",
        department: "Non-Ferrous",
        grade: "Titanium Grade 2",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=Ti+Gr2",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Sheets", "Rods"],
        description: "Workhorse grade. Good balance of strength/ductility.",
        chem: { "Ti": "99.2%" },
        phys: { "Density": "4.51 g/cm³" },
        specs: { standards: ["ASTM B338"], range: "Stock" },
        pros: "Standard chemical industry grade.",
        cons: "Lacks structural strength of Grade 5 alloy; highly reactive with oxygen at high temperatures."
    },
    {
        id: "ti-gr5",
        department: "Non-Ferrous",
        grade: "Titanium Grade 5",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=Ti+Gr5",
        category: "Bars & Rods",
        forms: ["Rods", "Plates"],
        description: "Ti-6Al-4V. Aerospace alloy.",
        chem: { "Al": "6%", "V": "4%" },
        phys: { "Density": "4.43 g/cm³" },
        specs: { standards: ["ASTM B348"], range: "Rods" },
        pros: "Very high strength.",
        cons: "Hard to form."
    },
    {
        id: "copper-c110",
        department: "Non-Ferrous",
        grade: "Copper Electrolytic (C110)",
        image: "https://placehold.co/600x400/b45309/ffffff?text=ETP+Copper",
        category: "Bars & Rods",
        forms: ["Bus Bars", "Rods"],
        description: "ETP Copper for electrical use.",
        chem: { "Cu": "99.9%" },
        phys: { "Density": "8.89 g/cm³" },
        specs: { standards: ["IS 191"], range: "Stock" },
        pros: "Highest conductivity.",
        cons: "Low structural tensile strength; prone to hydrogen embrittlement if annealed in reducing gas."
    },
    {
        id: "brass-c360",
        department: "Non-Ferrous",
        grade: "Free Cutting Brass (C360)",
        image: "https://placehold.co/600x400/d97706/ffffff?text=Brass+Hex",
        category: "Bars & Rods",
        forms: ["Hex Bars", "Rods"],
        description: "Standard machining brass.",
        chem: { "Cu": "60-63%", "Pb": "2.5-3.7%" },
        phys: { "Density": "8.50 g/cm³" },
        specs: { standards: ["ASTM B16"], range: "Stock" },
        pros: "Easiest to machine.",
        cons: "Lead content (2.5-3.7%) restricts its use in modern drinking water applications."
    },
    {
        id: "cuni-9010",
        department: "Non-Ferrous",
        grade: "Cupro Nickel 90/10",
        image: "https://placehold.co/600x400/b45309/ffffff?text=CuNi+90/10",
        category: "Pipes & Tubes",
        forms: ["Pipes", "Fittings"],
        description: "Copper-Nickel for marine pipes.",
        chem: { "Ni": "10%", "Fe": "1-2%" },
        phys: { "Density": "8.94 g/cm³" },
        specs: { standards: ["EEMUA 144"], range: "Stock" },
        pros: "Resists biofouling.",
        cons: "High susceptibility to shear erosion if seawater flow rate exceeds 3.5 m/s."
    },
    {
        id: "cuni-7030",
        department: "Non-Ferrous",
        grade: "Cupro Nickel 70/30",
        image: "https://placehold.co/600x400/b45309/ffffff?text=CuNi+70/30",
        category: "Pipes & Tubes",
        forms: ["Pipes"],
        description: "Higher strength marine alloy.",
        chem: { "Ni": "30%" },
        phys: { "Density": "8.94 g/cm³" },
        specs: { standards: ["ASTM B466"], range: "Custom" },
        pros: "High velocity seawater.",
        cons: "Significantly higher cost than 90/10; requires careful biofilm management."
    },
    {
        id: "alum-6061",
        department: "Non-Ferrous",
        grade: "Aluminum 6061 T6",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=Alu+6061",
        category: "Flat Products",
        forms: ["Plates", "Rods"],
        description: "Structural aluminum alloy.",
        chem: { "Mg": "0.8-1.2%", "Si": "0.4-0.8%" },
        phys: { "Density": "2.70 g/cm³" },
        specs: { standards: ["ASTM B209"], range: "Stock" },
        pros: "Good weldability.",
        cons: "Welding reduces localized strength at the heat-affected zone (HAZ) by 30-40%."
    },
    {
        id: "alum-5083",
        department: "Non-Ferrous",
        grade: "Aluminum 5083",
        image: "https://placehold.co/600x400/e2e8f0/1e293b?text=Alu+5083",
        category: "Flat Products",
        forms: ["Plates"],
        description: "Marine grade aluminum.",
        chem: { "Mg": "4-4.9%" },
        phys: { "Density": "2.66 g/cm³" },
        specs: { standards: ["ASTM B209"], range: "Plates" },
        pros: "Saltwater resistance.",
        cons: "Vulnerable to stress corrosion cracking if operated continuously above 65°C."
    },
    {
        id: "pb-bronze",
        department: "Non-Ferrous",
        grade: "Phosphor Bronze (C544)",
        image: "https://placehold.co/600x400/b45309/ffffff?text=Phos+Bronze",
        category: "Bars & Rods",
        forms: ["Rods", "Bushings"],
        description: "Spring quality bronze with excellent fatigue strength.",
        chem: { "Sn": "3.5-10%", "P": "0.01-0.35%" },
        phys: { "Density": "8.86 g/cm³" },
        specs: { standards: ["B139"], range: "Stock" },
        pros: "Wear resistance.",
        cons: "High raw material cost; lower electrical conductivity than pure copper."
    },
    {
        id: "tantalum",
        department: "Non-Ferrous",
        grade: "Tantalum (Ta)",
        image: "https://placehold.co/600x400/94a3b8/ffffff?text=Tantalum",
        category: "Flat Products",
        forms: ["Sheets", "Pipes", "Bars"],
        description: "Extreme corrosion resistance. Used in heat exchangers.",
        chem: { "Ta": "99.9%" },
        phys: { "Density": "16.69 g/cm³" },
        specs: { standards: ["ASTM B708"], range: "Imported" },
        pros: "Bio-compatible.",
        cons: "Extremely dense."
    },

    // =========================================================================
    // 8. FASTENERS, FITTINGS & FLANGES
    // =========================================================================
    {
        id: "bw-fittings",
        department: "Fittings",
        grade: "Buttweld Fittings (Elbow/Tee)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=BW+Fittings",
        category: "Fittings",
        forms: ["Elbow", "Tee", "Reducer", "Cap"],
        description: "SS and CS Buttweld Fittings.",
        chem: { "Grade": "ASME B16.9" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A403", "A234"], range: "Stock" },
        pros: "Standard piping connectors.",
        cons: "Requires professional radiography testing and skilled fit-up/welding."
    },
    {
        id: "forged-fittings",
        department: "Fittings",
        grade: "Forged Fittings (Socket/Threaded)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=Forged+Fittings",
        category: "Fittings",
        forms: ["Elbow", "Tee", "Union", "Plug"],
        description: "High pressure fittings (3000# / 6000#).",
        chem: { "Grade": "ASME B16.11" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A105", "A182"], range: "Stock" },
        pros: "High pressure.",
        cons: "Creates higher pressure drops than swept bends; increases pipeline weight."
    },
    {
        id: "flange-all",
        department: "Flanges",
        grade: "Industrial Flanges (WNRF/SORF)",
        image: "https://placehold.co/600x400/64748b/ffffff?text=Flanges",
        category: "Flanges",
        forms: ["WNRF", "SORF", "Blind", "Lap Joint"],
        description: "Pipe flanges in SS, CS, and Alloy Steel.",
        chem: { "Grade": "ASME B16.5" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A105", "A182"], range: "150# to 2500#" },
        pros: "Critical pipe connections.",
        cons: "Prone to gasket leaks if bolts are torque-tensioned unevenly."
    },
    {
        id: "fastener-ni-alloy",
        department: "Fasteners",
        grade: "Nickel Alloy Fasteners",
        image: "https://placehold.co/600x400/334155/ffffff?text=Ni+Bolts",
        category: "Fasteners",
        forms: ["Bolts", "Nuts", "Washers"],
        description: "Inconel, Monel, and Hastelloy Fasteners.",
        chem: { "Grade": "Special Alloy" },
        phys: { "Density": "8.44 g/cm³" },
        specs: { standards: ["ASTM F467", "DIN 933"], range: "M3-M56" },
        pros: "High temp & corrosion resistant.",
        cons: "Very high unit cost; prone to thread galling/seizing during assembly."
    },
    {
        id: "fastener-ss",
        department: "Fasteners",
        grade: "SS Fasteners (A2/A4)",
        image: "https://placehold.co/600x400/334155/ffffff?text=SS+Bolts",
        category: "Fasteners",
        forms: ["Bolts", "Nuts"],
        description: "304 (A2) and 316 (A4) Bolts.",
        chem: { "Grade": "ISO 3506" },
        phys: { "Density": "7.93 g/cm³" },
        specs: { standards: ["DIN 933", "DIN 934"], range: "M6-M64" },
        pros: "Corrosion free.",
        cons: "Subject to severe thread galling; lower shear strength than grade 8.8 carbon fasteners."
    },
    {
        id: "stud-b7",
        department: "Fasteners",
        grade: "Stud Bolt B7 / 2H",
        image: "https://placehold.co/600x400/334155/ffffff?text=B7+Studs",
        category: "Fasteners",
        forms: ["Studs"],
        description: "High temp pressure vessel bolting.",
        chem: { "Grade": "ASTM A193" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A193"], range: "Stock" },
        pros: "Oil & Gas standard.",
        cons: "Susceptible to hydrogen embrittlement if plated or coated improperly."
    },

    // =========================================================================
    // 9. SPECIALTY & WEAR PLATES
    // =========================================================================
    {
        id: "hardox-400",
        department: "Specialty",
        grade: "Hardox 400 (Abrasion Resistant)",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=Hardox+400",
        category: "Flat Products",
        forms: ["Plates"],
        description: "Wear resistant steel plate.",
        chem: { "Hardness": "400 HBW" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["AR 400"], range: "Plates" },
        pros: "Extended wear life.",
        cons: "Hard to drill."
    },
    {
        id: "hardox-500",
        department: "Specialty",
        grade: "Hardox 500",
        image: "https://placehold.co/600x400/1e293b/ffffff?text=Hardox+500",
        category: "Flat Products",
        forms: ["Plates"],
        description: "Extra hard wear plate.",
        chem: { "Hardness": "500 HBW" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["AR 500"], range: "Plates" },
        pros: "Extreme wear.",
        cons: "Very hard to machine."
    },
    {
        id: "corten-a",
        department: "Specialty",
        grade: "Corten Steel A (IRS M41)",
        image: "https://placehold.co/600x400/b45309/ffffff?text=Corten+A",
        category: "Flat Products",
        forms: ["Plates"],
        description: "Weathering steel. Forms protective rust layer.",
        chem: { "Cu": "0.25-0.55%", "Cr": "0.5-1.25%" },
        phys: { "Density": "7.85 g/cm³" },
        specs: { standards: ["ASTM A242"], range: "Stock" },
        pros: "No painting needed.",
        cons: "Rust water runoff will bleed and stain adjacent concrete, sidewalks, and masonry."
    }
];