// Tatvam Overseas — Unified Tailwind Configuration
// Shared design tokens from STEELCORP template
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "steel-deep": "#0F172A",
        "emerald-accent": "#10B981",
        "emerald-hover": "#059669",
        "slate-muted": "#475569",
        "surface": "#f7f9fb",
        "surface-alt": "#F8FAFC",
        "surface-bright": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-variant": "#e0e3e5",
        "surface-container": "#eceef0",
        "surface-container-low": "#f2f4f6",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1e",
        "on-surface-variant": "#45464d",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "outline-variant": "#c6c6cd",
        "outline": "#76777d",
        "primary-container": "#131b2e",
        "tertiary-container": "#0d1c2e",
        "secondary": "#006c49",
        "on-tertiary-container": "#77859a",
        "on-primary-container": "#7c839b",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "tertiary-fixed": "#d5e3fc",
        "tertiary-fixed-dim": "#b9c7df",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#bec6e0",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-tint": "#565e74",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        base: "8px",
        "section-gap": "120px",
        gutter: "32px",
        "margin-desktop": "64px",
        "container-max": "1280px",
      },
      fontFamily: {
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg-mobile": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "headline-md": ["Montserrat"],
        "body-lg": ["Inter"],
        "display-lg": ["Montserrat"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "600" },
        ],
        "headline-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-md": ["30px", { lineHeight: "38px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "64px",
          {
            lineHeight: "72px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
};
